# Visual Odometry 

In [2]:
# tools
from tools import *
import pandas as pd 
import numpy as np 
import cv2 as cv 
import os 

# visualisation 
import matplotlib
matplotlib.use('TkAgg') 
import matplotlib.pyplot as plt 
from IPython.display import clear_output



## Feature detector 

For the feature detectioon we are going to use ORB algorithm

In [4]:
# frames path
num_seq   = "00"
dir_path  = "/Users/sergio/Documents/kitti/gray_images/sequences/" + num_seq + "/image_0"
img_list  = sorted(os.listdir(dir_path))

# read a frame
num_frame = 0
img       = cv.imread(os.path.join(dir_path, img_list[num_frame]), cv.IMREAD_GRAYSCALE)

# create ORB object 
max_num_features       = 3000
orb                    = cv.ORB_create(max_num_features)
keypoints, descriptors = orb.detectAndCompute(img, None)

# draw features 
img2 = cv.drawKeypoints(img, keypoints, None, color=(0,255,0), flags=0)
plt.figure(figsize=(20, 5))
plt.imshow(img2) 
plt.axis("off")
plt.show()

## Feature matching 

In order to match correspondances between features we use the FLANN algorithm 

In [5]:
img1 = cv.imread(os.path.join(dir_path, img_list[0]), cv.IMREAD_GRAYSCALE)
img2 = cv.imread(os.path.join(dir_path, img_list[1]), cv.IMREAD_GRAYSCALE)

max_num_features         = 1000
orb                      = cv.ORB_create(max_num_features)
keypoints1, descriptors1 = orb.detectAndCompute(img1, None)
keypoints2, descriptors2 = orb.detectAndCompute(img2, None)

# FLANN parameters for LSH (suitable for binary descriptors like ORB)
FLANN_INDEX_LSH = 6
index_params    = dict(
                    algorithm         = FLANN_INDEX_LSH,
                    table_number      = 6,  
                    key_size          = 12,     
                    multi_probe_level = 1
                )  
search_params   = dict(checks=50)  # or pass empty dictionary

# Create FLANN-based matcher
flann   = cv.FlannBasedMatcher(index_params, search_params)
matches = flann.knnMatch(descriptors1, descriptors2, k=2)

# Apply ratio test to filter good matches (Lowe's ratio test)
good_matches = []
for m, n in matches:
    if m.distance < 0.8 * n.distance:
        good_matches.append(m)

# Draw matches
img_matches = cv.drawMatches(img1, keypoints1, img2, keypoints2, good_matches, None, flags=cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

plt.figure(figsize=(20, 5))
plt.imshow(img_matches) 
plt.axis("off")
plt.show()

## Recover pose

In [7]:
path_calib_seq = "/Users/sergio/Documents/kitti/gray_images/sequences/" + num_seq + "/calib.txt"
P, K           = read_calib(path_calib_seq)

# Find corresponding points 
pts1 = []
pts2 = []
 
# ratio test as per Lowe's paper
for i, (m, n) in enumerate(matches):
    if m.distance < 0.8 * n.distance:
        pts2.append(keypoints2[m.trainIdx].pt)
        pts1.append(keypoints1[m.queryIdx].pt)

pts1 = np.int32(pts1)
pts2 = np.int32(pts2)
E, mask = cv.findEssentialMat(pts1, pts2, cameraMatrix=K)

# recover pose 
_, R, T, mask = cv.recoverPose(E, pts1, pts2, cameraMatrix=K)

## Draw trajectories 

In [9]:
poses_path = "/Users/sergio/Documents/kitti/dataset_poses/poses/00.txt"
poses_df   = pd.read_csv(poses_path, header=None, sep=' ')

poses   = poses_df.apply(lambda row: read_pose(row.values), axis=1)
img_pts = []
for pose in poses:
    _ , T = pose
    x, y, z = T
    img_pts.append(np.array([x, z]))

img_pts = np.stack(img_pts)

plt.plot(img_pts[:, 0], img_pts[:, 1])
plt.title('Trayectory sequence:' + num_seq)
plt.show()

# Bundle Adjustment 

In [5]:
import torch 

In [6]:
print("Rotation: \n", R, R.shape)
print("Translation: \n", T)

Rotation: 
 [[ 0.99997938  0.00628304  0.00132799]
 [-0.00628542  0.99997864  0.00179399]
 [-0.00131669 -0.0018023   0.99999751]] (3, 3)
Translation: 
 [[ 0.16287753]
 [-0.02853452]
 [-0.98623359]]


In [7]:
from backend import BundleAdjustment
import argparse as arg

args = arg
args.image_height = img.shape[0] 
args.image_width  = img.shape[1]
args.size_window  = 2
args.lr           = 3e-4
args.epochs       = 50 
bundle_adjustment = BundleAdjustment(args)


In [8]:
measures1 = torch.tensor([kp.pt for kp in keypoints1])
measures2 = torch.tensor([kp.pt for kp in keypoints2])
measure_pts = torch.stack([measures1, measures2])
measure_pts.shape

torch.Size([2, 1000, 2])

In [12]:
T0 = torch.zeros(3, 1, dtype=torch.float32)
print(T0.shape, T.shape)
translations = torch.stack([T0, torch.tensor(T)])


torch.Size([3, 1]) (3, 1)


In [9]:
R0 = torch.eye(3, dtype=torch.float32)
T0 = torch.zeros(3, 1, dtype=torch.float32)

rotations = torch.stack([R0, torch.tensor(R)])
translations = torch.stack([T0, torch.tensor(T)])
points_3d = torch.rand(max_num_features, 3, 1)
K_pt = torch.tensor(K).unsqueeze(dim=2).transpose(0, -1)

bundle_adjustment.rotations = rotations
bundle_adjustment.translations = translations
bundle_adjustment.points_3d = points_3d
bundle_adjustment.K = K_pt
bundle_adjustment.measure_pts = measure_pts

bundle_adjustment.run()

Epoch 1/50, Reprojection Error: 0.0
Epoch 50/50, Reprojection Error: -0.007350003346800804


In [11]:
print("rotation after BA:\n", bundle_adjustment.rotations)
print("translations after BA:\n", bundle_adjustment.translations)

rotation after BA:
 tensor([[[ 1.0000,  0.0000,  0.0000],
         [ 0.0000,  1.0000,  0.0000],
         [ 0.0000,  0.0000,  1.0000]],

        [[ 1.0000,  0.0063,  0.0013],
         [-0.0063,  1.0000,  0.0018],
         [-0.0013, -0.0018,  1.0000]]], dtype=torch.float64)
translations after BA:
 tensor([[[ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[ 0.1629],
         [-0.0285],
         [-0.9862]]], dtype=torch.float64)


In [12]:
bundle_adjustment.points_3\


tensor([[[0.0879],
         [0.0770],
         [0.1964]],

        [[0.2554],
         [0.8634],
         [0.5748]],

        [[0.7290],
         [0.2669],
         [0.0660]],

        ...,

        [[0.8414],
         [0.4707],
         [0.8033]],

        [[0.0203],
         [0.8312],
         [0.9712]],

        [[0.7264],
         [0.4438],
         [0.2641]]])

In [13]:
import munch

cameras = dict()
cameras[0] = munch.munchify({"R" : 1, "T" : 1})

In [38]:
import numpy as np
T = np.random.rand(10)
(T[None].transpose()).shape

(10, 1)

In [8]:
import evo.tools.plot as evoplt

evoplt.PlotMode.xy

<PlotMode.xy: 'xy'>

In [3]:
import evo.tools

print(dir(evo))


['EvoException', 'NullHandler', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'logging', 'tools']
